source 'https://rubygems.org'

gem 'telegram-bot-ruby', :git => 'git@github.com:atipugin/telegram-bot-ruby.git'
gem 'activerecord'
gem 'i18n'
gem 'rake'
gem 'mysql2'
gem 'pry'
gem 'pry-byebug'
gem 'jenkins_api_client'
